files: ''
repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--skip-string-normalization, --line-length=100, ./src]
        language_version: python3.11

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.261'
    hooks:
      - id: ruff
        args: [--fix, ./src]
        language_version: python3.11
