version: '3.9'

services:
  db:
    image: postgres:15.1-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  bot:
    build:
      dockerfile: docker/Dockerfile.bot
      context: .
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./src:/app

volumes:
  postgres_data: